package Coleccion.ListaPackage;

/**
* Coleccion/ListaPackage/NoExisteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/

public final class NoExisteHolder implements org.omg.CORBA.portable.Streamable
{
  public Coleccion.ListaPackage.NoExiste value = null;

  public NoExisteHolder ()
  {
  }

  public NoExisteHolder (Coleccion.ListaPackage.NoExiste initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Coleccion.ListaPackage.NoExisteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Coleccion.ListaPackage.NoExisteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Coleccion.ListaPackage.NoExisteHelper.type ();
  }

}
