package Coleccion.ListaPackage;


/**
* Coleccion/ListaPackage/NoExisteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/

abstract public class NoExisteHelper
{
  private static String  _id = "IDL:Coleccion/Lista/NoExiste:1.0";

  public static void insert (org.omg.CORBA.Any a, Coleccion.ListaPackage.NoExiste that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Coleccion.ListaPackage.NoExiste extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "explicacion",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (Coleccion.ListaPackage.NoExisteHelper.id (), "NoExiste", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Coleccion.ListaPackage.NoExiste read (org.omg.CORBA.portable.InputStream istream)
  {
    Coleccion.ListaPackage.NoExiste value = new Coleccion.ListaPackage.NoExiste ();
    // read and discard the repository ID
    istream.read_string ();
    value.explicacion = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Coleccion.ListaPackage.NoExiste value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_string (value.explicacion);
  }

}
