package Coleccion.ListaPackage;


/**
* Coleccion/ListaPackage/NoExiste.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/

public final class NoExiste extends org.omg.CORBA.UserException
{
  public String explicacion = null;

  public NoExiste ()
  {
    super(NoExisteHelper.id());
  } // ctor

  public NoExiste (String _explicacion)
  {
    super(NoExisteHelper.id());
    explicacion = _explicacion;
  } // ctor


  public NoExiste (String $reason, String _explicacion)
  {
    super(NoExisteHelper.id() + "  " + $reason);
    explicacion = _explicacion;
  } // ctor

} // class NoExiste
