
all: Money.class MoneyTest.class Main.class ArrayListTest.class

Money.class: Money.java 
	javac $<

MoneyTest.class: MoneyTest.java
	javac $<

Main.class: Main.java
	javac $<

ArrayListTest.class: ArrayListTest.java
	javac $<