package Registrador;


/**
* Registrador/_RegistrarStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/

public class _RegistrarStub extends org.omg.CORBA.portable.ObjectImpl implements Registrador.Registrar
{

  public Registrador.HolaMundo obtenerHola (String nombre)
  {
    org.omg.CORBA.portable.InputStream $in = null;
    try {
       org.omg.CORBA.portable.OutputStream $out = _request ("obtenerHola", true);
       $out.write_string (nombre);
       $in = _invoke ($out);
       Registrador.HolaMundo $result = Registrador.HolaMundoHelper.read ($in);
       return $result;
    } catch (org.omg.CORBA.portable.ApplicationException $ex) {
       $in = $ex.getInputStream ();
       String _id = $ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException $rm) {
       return obtenerHola (nombre);
    } finally {
        _releaseReply ($in);
    }
  } // obtenerHola

  public void removeHola (String nombre)
  {
    org.omg.CORBA.portable.InputStream $in = null;
    try {
       org.omg.CORBA.portable.OutputStream $out = _request ("removeHola", true);
       $out.write_string (nombre);
       $in = _invoke ($out);
    } catch (org.omg.CORBA.portable.ApplicationException $ex) {
       $in = $ex.getInputStream ();
       String _id = $ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException $rm) {
       removeHola (nombre);
    } finally {
        _releaseReply ($in);
    }
  } // removeHola

  public void registrarHola (String nombre, Registrador.HolaMundo hola)
  {
    org.omg.CORBA.portable.InputStream $in = null;
    try {
       org.omg.CORBA.portable.OutputStream $out = _request ("registrarHola", true);
       $out.write_string (nombre);
       Registrador.HolaMundoHelper.write ($out, hola);
       $in = _invoke ($out);
    } catch (org.omg.CORBA.portable.ApplicationException $ex) {
       $in = $ex.getInputStream ();
       String _id = $ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException $rm) {
       registrarHola (nombre, hola);
    } finally {
        _releaseReply ($in);
    }
  } // registrarHola

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Registrador/Registrar:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _RegistrarStub
