package Registrador;

/**
* Registrador/HolaMundoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/


/* Definición de la clase lista */
public final class HolaMundoHolder implements org.omg.CORBA.portable.Streamable
{
  public Registrador.HolaMundo value = null;

  public HolaMundoHolder ()
  {
  }

  public HolaMundoHolder (Registrador.HolaMundo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Registrador.HolaMundoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Registrador.HolaMundoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Registrador.HolaMundoHelper.type ();
  }

}
