package Registrador;


/**
* Registrador/HolaMundoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/


/* Definición de la clase lista */
abstract public class HolaMundoHelper
{
  private static String  _id = "IDL:Registrador/HolaMundo:1.0";

  public static void insert (org.omg.CORBA.Any a, Registrador.HolaMundo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Registrador.HolaMundo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Registrador.HolaMundoHelper.id (), "HolaMundo");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Registrador.HolaMundo read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HolaMundoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Registrador.HolaMundo value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Registrador.HolaMundo narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Registrador.HolaMundo)
      return (Registrador.HolaMundo)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Registrador._HolaMundoStub stub = new Registrador._HolaMundoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
