package Registrador;


/**
* Registrador/HolaMundoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/


/* Definición de la clase lista */
public interface HolaMundoOperations 
{
  String decirHola ();
  void shutdown ();
} // interface HolaMundoOperations
