package Registrador;


/**
* Registrador/HolaMundo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/


/* Definición de la clase lista */
public interface HolaMundo extends HolaMundoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HolaMundo
