package Registrador;


/**
* Registrador/RegistrarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/

public interface RegistrarOperations 
{
  Registrador.HolaMundo obtenerHola (String nombre);
  void removeHola (String nombre);
  void registrarHola (String nombre, Registrador.HolaMundo hola);
} // interface RegistrarOperations
