package Registrador;


/**
* Registrador/RegistrarHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/

abstract public class RegistrarHelper
{
  private static String  _id = "IDL:Registrador/Registrar:1.0";

  public static void insert (org.omg.CORBA.Any a, Registrador.Registrar that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Registrador.Registrar extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Registrador.RegistrarHelper.id (), "Registrar");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Registrador.Registrar read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RegistrarStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Registrador.Registrar value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Registrador.Registrar narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Registrador.Registrar)
      return (Registrador.Registrar)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Registrador._RegistrarStub stub = new Registrador._RegistrarStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
