package Registrador;


/**
* Registrador/RegistrarPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/

public abstract class RegistrarPOA extends org.omg.PortableServer.Servant
 implements Registrador.RegistrarOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("obtenerHola", new java.lang.Integer (0));
    _methods.put ("removeHola", new java.lang.Integer (1));
    _methods.put ("registrarHola", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Registrador/Registrar/obtenerHola
       {
         String nombre = in.read_string ();
         Registrador.HolaMundo $result = null;
         $result = this.obtenerHola (nombre);
         out = $rh.createReply();
         Registrador.HolaMundoHelper.write (out, $result);
         break;
       }

       case 1:  // Registrador/Registrar/removeHola
       {
         String nombre = in.read_string ();
         this.removeHola (nombre);
         out = $rh.createReply();
         break;
       }

       case 2:  // Registrador/Registrar/registrarHola
       {
         String nombre = in.read_string ();
         Registrador.HolaMundo hola = Registrador.HolaMundoHelper.read (in);
         this.registrarHola (nombre, hola);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Registrador/Registrar:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Registrar _this() 
  {
    return RegistrarHelper.narrow(
    super._this_object());
  }

  public Registrar _this(org.omg.CORBA.ORB orb) 
  {
    return RegistrarHelper.narrow(
    super._this_object(orb));
  }


} // class RegistrarPOA
