package Registrador;

/**
* Registrador/RegistrarHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Registrador.idl
* miércoles 19 de febrero de 2003 14H05' COT
*/

public final class RegistrarHolder implements org.omg.CORBA.portable.Streamable
{
  public Registrador.Registrar value = null;

  public RegistrarHolder ()
  {
  }

  public RegistrarHolder (Registrador.Registrar initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Registrador.RegistrarHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Registrador.RegistrarHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Registrador.RegistrarHelper.type ();
  }

}
