/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apress.isf.spring;

public class HelloWorldMessage implements MessageService {
    public String getMessage() {
        return "Hello World";
    }
}
