package Coleccion;


/**
* Coleccion/_ListaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/


/* Definición de la clase lista */
public class _ListaStub extends org.omg.CORBA.portable.ObjectImpl implements Coleccion.Lista
{

  public boolean Adicionar (String nombre)
  {
    org.omg.CORBA.portable.InputStream $in = null;
    try {
       org.omg.CORBA.portable.OutputStream $out = _request ("Adicionar", true);
       $out.write_string (nombre);
       $in = _invoke ($out);
       boolean $result = $in.read_boolean ();
       return $result;
    } catch (org.omg.CORBA.portable.ApplicationException $ex) {
       $in = $ex.getInputStream ();
       String _id = $ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException $rm) {
       return Adicionar (nombre);
    } finally {
        _releaseReply ($in);
    }
  } // Adicionar

  public void Borrar (String nombre) throws Coleccion.ListaPackage.NoExiste
  {
    org.omg.CORBA.portable.InputStream $in = null;
    try {
       org.omg.CORBA.portable.OutputStream $out = _request ("Borrar", true);
       $out.write_string (nombre);
       $in = _invoke ($out);
    } catch (org.omg.CORBA.portable.ApplicationException $ex) {
       $in = $ex.getInputStream ();
       String _id = $ex.getId ();
       if (_id.equals ("IDL:Coleccion/Lista/NoExiste:1.0"))
          throw Coleccion.ListaPackage.NoExisteHelper.read ($in);
       else
            throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException $rm) {
       Borrar (nombre);
    } finally {
        _releaseReply ($in);
    }
  } // Borrar

  public boolean Consultar (String nombre)
  {
    org.omg.CORBA.portable.InputStream $in = null;
    try {
       org.omg.CORBA.portable.OutputStream $out = _request ("Consultar", true);
       $out.write_string (nombre);
       $in = _invoke ($out);
       boolean $result = $in.read_boolean ();
       return $result;
    } catch (org.omg.CORBA.portable.ApplicationException $ex) {
       $in = $ex.getInputStream ();
       String _id = $ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException $rm) {
       return Consultar (nombre);
    } finally {
        _releaseReply ($in);
    }
  } // Consultar

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Coleccion/Lista:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ListaStub
