package Coleccion;

/**
* Coleccion/ListaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/


/* Definición de la clase lista */
public final class ListaHolder implements org.omg.CORBA.portable.Streamable
{
  public Coleccion.Lista value = null;

  public ListaHolder ()
  {
  }

  public ListaHolder (Coleccion.Lista initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Coleccion.ListaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Coleccion.ListaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Coleccion.ListaHelper.type ();
  }

}
