package Coleccion;


/**
* Coleccion/ListaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/


/* Definición de la clase lista */
abstract public class ListaHelper
{
  private static String  _id = "IDL:Coleccion/Lista:1.0";

  public static void insert (org.omg.CORBA.Any a, Coleccion.Lista that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Coleccion.Lista extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Coleccion.ListaHelper.id (), "Lista");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Coleccion.Lista read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ListaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Coleccion.Lista value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Coleccion.Lista narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Coleccion.Lista)
      return (Coleccion.Lista)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Coleccion._ListaStub stub = new Coleccion._ListaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
