package Coleccion;


/**
* Coleccion/ListaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/


/* Definición de la clase lista */
public interface ListaOperations 
{
  boolean Adicionar (String nombre);
  void Borrar (String nombre) throws Coleccion.ListaPackage.NoExiste;
  boolean Consultar (String nombre);
} // interface ListaOperations
