package Coleccion;


/**
* Coleccion/ListaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/


/* Definición de la clase lista */
public abstract class ListaPOA extends org.omg.PortableServer.Servant
 implements Coleccion.ListaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("Adicionar", new java.lang.Integer (0));
    _methods.put ("Borrar", new java.lang.Integer (1));
    _methods.put ("Consultar", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Coleccion/Lista/Adicionar
       {
         String nombre = in.read_string ();
         boolean $result = false;
         $result = this.Adicionar (nombre);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Coleccion/Lista/Borrar
       {
         try {
           String nombre = in.read_string ();
           this.Borrar (nombre);
           out = $rh.createReply();
         } catch (Coleccion.ListaPackage.NoExiste $ex) {
           out = $rh.createExceptionReply ();
           Coleccion.ListaPackage.NoExisteHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // Coleccion/Lista/Consultar
       {
         String nombre = in.read_string ();
         boolean $result = false;
         $result = this.Consultar (nombre);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Coleccion/Lista:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Lista _this() 
  {
    return ListaHelper.narrow(
    super._this_object());
  }

  public Lista _this(org.omg.CORBA.ORB orb) 
  {
    return ListaHelper.narrow(
    super._this_object(orb));
  }


} // class ListaPOA
