package Coleccion;


/**
* Coleccion/Lista.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Lista.idl
* lunes 1 de septiembre de 2003 14H31' COT
*/


/* Definición de la clase lista */
public interface Lista extends ListaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Lista
